version: "3"
networks:
  gorniacnet:
    external:
      name: gorniacglobalnet

services:
  postgres:
    container_name: postgres_container
    image: 'postgres:15'
    restart: always
    environment:
      container_name: postgres_container
      POSTGRES_DB: gorniac
      POSTGRES_USER: root
      POSTGRES_PASSWORD: gorniacisgood
      PGDATA: /tmp
    volumes:
      - ./init database:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      gorniacnet:
        aliases:
          - posgres.gorniacnet

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "kudrsv.kudrsv@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "rootgorniac"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      gorniacnet:
        aliases:
          - pgadmin.gorniacnet

  fastapi:
    build: .
    image: gorniac_shop
    container_name: fastapi_container
    links:
      - postgres
    volumes:
      - ./img_docker:/core/static/images
    ports:
      - "8000:8000"
    networks:
      gorniacnet:
        aliases:
          - fastapi.gorniacnet
