version: "1.0.0"
services:
  postgres:
    container_name: postgres_container
    image: 'postgres:15'
    restart: always
    environment:
      container_name: postgres_container
      POSTGRES_DB: gorniac
      POSTGRES_USER: root
      POSTGRES_PASSWORD: gorniacisgood
      PGDATA: /tmp
    volumes:
      - ./init database:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "kudrsv.kudrsv@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "rootgorniac"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  fastapi:
    build: .
    image: gorniac_shop
    container_name: fastapi_container
    links:
      - postgres
    volumes:
      - ./app:/app
    ports:
      - 8000:8000